/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:bfbe916c-07f7-4afd-86c8-53d7f02b4c57",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_5mfRhu5La",
    "aws_user_pools_web_client_id": "v847t79b46r1219du2973kmho",
    "oauth": {}
};


export default awsmobile;
